"use strict";
const $=s=>document.querySelector(s);
function date(v){if(!v)return"Noch nicht vorhanden";const x=String(v).includes("T")?v:String(v).replace(" ","T")+"Z",d=new Date(x);return Number.isNaN(d.getTime())?"Noch nicht vorhanden":new Intl.DateTimeFormat("de-AT",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function duration(s){s=Math.max(0,Number(s)||0);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h} Std. ${m} Min.`:m?`${m} Min.`:`${s} Sek.`}
function text(s,v){const e=$(s);if(e)e.textContent=v}
function usage(items){const list=$("#accountUsageList");if(!list)return;list.innerHTML="";if(!items?.length){list.innerHTML='<p class="empty-message">Noch keine Nutzungsdaten vorhanden.</p>';return}items.forEach(i=>{const row=document.createElement("div");row.className="usage-row";const info=document.createElement("div"),title=document.createElement("strong"),visits=document.createElement("span"),time=document.createElement("strong");title.textContent=i.title||i.chakraKey||"Chakra-Seite";const count=Number(i.visitCount)||0;visits.textContent=`${count} Aufruf${count===1?"":"e"}`;time.textContent=duration(i.durationSeconds);info.append(title,visits);row.append(info,time);list.append(row)})}
async function load(){const message=$("#accountMessage");try{const r=await fetch("/api/me/account",{credentials:"same-origin",cache:"no-store"}),raw=await r.text();let data;try{data=JSON.parse(raw)}catch{throw Error("Die Konto-API hat keine gültige Antwort geliefert.")}if(!r.ok||!data.authenticated)throw Error(data.error||"Du bist nicht angemeldet.");const u=data.user||{};text("#accountDisplayName",u.displayName||"Dein persönlicher Bereich");text("#accountUsername",u.username||"Nicht vorhanden");text("#accountEmail",u.email||"Nicht hinterlegt");text("#accountCreatedAt",date(u.createdAt));text("#accountFirstLogin",date(u.firstLoginAt));text("#accountLastLogin",date(u.lastLoginAt));text("#accountTotalUsage",duration(u.totalDurationSeconds));let access="Nicht festgelegt";if(u.role==="admin")access="Vollzugriff";else if(u.remainingDays<0)access="Zugang abgelaufen";else if(u.remainingDays===0)access="Läuft heute ab";else if(u.remainingDays===1)access="Noch 1 Tag";else if(u.remainingDays!=null)access=`Noch ${u.remainingDays} Tage`;text("#accountAccess",access);const renew=$("#accountRenewLink");if(renew)renew.hidden=!(u.role!=="admin"&&u.remainingDays!=null&&u.remainingDays<=7);usage(data.usage||[]);if(message)message.textContent=""}catch(e){console.error(e);if(message)message.textContent=e.message;if(String(e.message).includes("angemeldet"))setTimeout(()=>location.href="/login.html",800)}}
const out=$("#accountLogoutButton");if(out)out.onclick=async()=>{try{await fetch("/api/auth/logout",{method:"POST",credentials:"same-origin"})}finally{location.href="/index.html"}};
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",load):load();

