"use strict";
const $=s=>document.querySelector(s),form=$("#createUserForm"),msg=$("#adminMessage"),session=$("#adminSessionText"),list=$("#usersList"),loading=$("#usersLoading"),empty=$("#usersEmpty"),tpl=$("#userCardTemplate");
function message(t,ok=false){msg.textContent=t||"";msg.classList.toggle("success",ok)}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}}),text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={error:text}}if(r.status===401||r.status===403){location.href="/login.html";throw Error("Nicht autorisiert.")}if(!r.ok)throw Error(d.error||"Anfrage fehlgeschlagen.");return d}
const date=v=>{if(!v)return"Nicht festgelegt";const d=new Date(v);return isNaN(d)?v:new Intl.DateTimeFormat("de-AT",{dateStyle:"medium",timeStyle:String(v).includes("T")||String(v).includes(" ")?"short":undefined}).format(d)};
const dateInput=v=>v?String(v).slice(0,10):"";
const days=v=>v?Math.ceil((new Date(`${String(v).slice(0,10)}T23:59:59`)-Date.now())/86400000):null;
const duration=s=>{s=Math.max(0,Number(s)||0);const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return h?`${h} Std. ${m} Min.`:m?`${m} Min.`:`${s} Sek.`};
const checked=(root,name)=>[...root.querySelectorAll(`input[name="${name}"]`)].filter(x=>x.checked).map(x=>x.value);
async function sessionCheck(){const d=await api("/api/auth/session");if(!d.authenticated||d.user.role!=="admin"){location.href="/login.html";return false}session.textContent=`Angemeldet als ${d.user.displayName||d.user.username} · Vollzugriff auf alle Chakra-Seiten`;return true}
function usage(el,items=[]){el.innerHTML="";if(!items.length){el.textContent="Noch keine Nutzungsdaten vorhanden.";return}items.forEach(i=>{const r=document.createElement("div");r.className="usage-item";r.innerHTML=`<strong>${i.title||i.chakraTitle||i.chakraKey}</strong><span>${duration(i.durationSeconds??i.duration_seconds)}</span>`;el.append(r)})}
function render(u){const f=tpl.content.cloneNode(true),c=f.querySelector(".user-card");c.dataset.userId=u.id;c.querySelector(".user-display-name").textContent=u.displayName||u.display_name||u.username;c.querySelector(".user-username").textContent=`@${u.username}`;c.querySelector(".user-email").textContent=u.email||"Keine E-Mail hinterlegt";const exp=u.accessExpiresAt||u.access_expires_at,last=u.lastLoginAt||u.last_login_at,left=days(exp),active=Boolean(u.isActive??u.is_active);c.querySelector(".user-access-expires").textContent=date(exp);c.querySelector(".user-last-login").textContent=last?date(last):"Noch keine Anmeldung";c.querySelector(".user-days-remaining").textContent=left===null?"Nicht festgelegt":left<0?"Abgelaufen":`${left} Tag${left===1?"":"e"}`;const st=c.querySelector(".user-status");st.textContent=!active?"Inaktiv":left!==null&&left<0?"Abgelaufen":"Aktiv";st.classList.toggle("inactive",!active);st.classList.toggle("expired",active&&left!==null&&left<0);c.querySelector(".edit-access-expires").value=dateInput(exp);c.querySelector(".edit-is-active").checked=active;const grants=new Set(u.chakras||u.chakraKeys||[]);c.querySelectorAll('input[name="userChakras"]').forEach(x=>x.checked=grants.has(x.value));usage(c.querySelector(".usage-list"),u.usage||[]);c.querySelector(".save-user-button").onclick=()=>save(c);c.querySelector(".delete-user-button").onclick=()=>remove(u);list.append(f)}
async function load(){loading.hidden=false;empty.hidden=true;list.innerHTML="";try{const d=await api("/api/admin/users"),users=(d.users||[]).filter(u=>u.role!=="admin");loading.hidden=true;empty.hidden=users.length>0;users.forEach(render)}catch(e){loading.hidden=true;message(e.message)}}
async function create(e){e.preventDefault();try{await api("/api/admin/user-create",{method:"POST",body:JSON.stringify({displayName:form.displayName.value.trim(),username:form.username.value.trim(),email:form.email.value.trim(),password:form.password.value,accessExpiresAt:form.accessExpiresAt.value,isActive:form.isActive.checked,chakras:checked(form,"chakras")})});form.reset();form.isActive.checked=true;message("Benutzer wurde angelegt.",true);await load()}catch(e){message(e.message)}}
async function save(c){const body={userId:Number(c.dataset.userId),accessExpiresAt:c.querySelector(".edit-access-expires").value,isActive:c.querySelector(".edit-is-active").checked,chakras:checked(c,"userChakras")},p=c.querySelector(".edit-password").value;if(p)body.password=p;try{await api("/api/admin/user-update",{method:"PUT",body:JSON.stringify(body)});message("Änderungen wurden gespeichert.",true);await load()}catch(e){message(e.message)}}
async function remove(u){if(!confirm(`Benutzer „${u.displayName||u.display_name||u.username}“ wirklich löschen?`))return;try{await api("/api/admin/user-delete",{method:"DELETE",body:JSON.stringify({userId:u.id})});message("Benutzer wurde gelöscht.",true);await load()}catch(e){message(e.message)}}
async function logout(){try{await fetch("/api/auth/logout",{method:"POST"})}finally{location.href="/login.html"}}
form.addEventListener("submit",create);$("#reloadUsersButton").onclick=load;$("#logoutButton").onclick=logout;(async()=>{try{if(await sessionCheck())await load()}catch(e){message(e.message)}})();
